//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BorrowTools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int locationID { get; set; }
        public string locationName { get; set; }
        public string locationManager { get; set; }
        public string locationPhoneNumber { get; set; }
    }
}
