//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BorrowTools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tool
    {
        public int toolID { get; set; }
        public string toolName { get; set; }
        public string toolBrand { get; set; }
        public string toolNotes { get; set; }
        public Nullable<bool> toolAvailable { get; set; }
    }
}
